#!/usr/bin/env bash 
# very long comment

PID_FILE="/tmp/myscript.pid"
echo $$ > "$PID_FILE"

handle_sigterm() {
	echo "I hate the kill command"
	rm -f "$PID_FILE"
	exit 0
}

handle_sigint() {
	echo "Y U no love me?!"
}

trap 'handle_sigterm' SIGTERM SIGQUIT
trap 'hangle_sigint' SIGINT

while true 
do
	echo "To infinity and beyond"
	sleep 2 & wait $!
done 
