#!/usr/bin/env bash 
# very long comment
echo $$ > /tmp/myscript.pid

trap "echo 'Y U no love me ?!'" SIGINT

trap "rm /tmp/myscrript.pid; exit" SIGQUIT

trap "echo 'I hate the kill command'; rm /tmp/myscripts.pid; exit" SIGTERM 

while true 
do
	echo "To infinity and beyond"
	sleep 2
done 
